apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: datastore3
  region: ap-south-1

managedNodeGroups:
  - name: datastore30-ng-1
    instanceType: t2.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: ap-noddy
    availabilityZones: ["ap-south-1a", "ap-south-1b"]
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        efs: true

