apiVersion: v1
kind: Service
metadata:
  name: datastore-backend-svc
  namespace: backend
spec:
  selector:
    type: backend
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  type: ClusterIP

