apiVersion: v1
kind: ConfigMap
metadata:
  name: datastore-be-cm
  namespace: backend
data:
  mysqlHost: jdbc:mysql://wing.cj26osqccn6b.ap-south-1.rds.amazonaws.com:3306/datastore?createDatabaseIfNotExist=true
  mysqlUname: root