apiVersion: apps/v1
kind: Deployment
metadata:
  name: datastore-backend
  namespace: backend
  labels:
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      name: datastore-backend
      labels:
        type: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8084"
    spec:
      containers:
        - name: datastore-backend
          image: 8072388539/datastore:v35.0
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: datastore-be-cm
                  key: mysqlHost
            - name: MYSQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: datastore-be-cm
                  key: mysqlUname
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datastore-be-secret
                  key: mysqlPassword
          ports:
            - containerPort: 8084
          resources:
            requests:
              cpu: 100m
              memory: "500Mi"
            limits:
              cpu: 1
              memory: "1Gi"
#          livenessProbe:
#            httpGet:
#              path: /actuator
#              port: 8084
#            initialDelaySeconds: 120
#            periodSeconds: 30
#            timeoutSeconds: 5
#            failureThreshold: 5
#          readinessProbe:
#            httpGet:
#              path: /actuator
#              port: 8084
#            initialDelaySeconds: 10
#            periodSeconds: 5
#            timeoutSeconds: 5
#            failureThreshold: 3
#          startupProbe:
#            httpGet:
#              path: /actuator
#              port: 8084
#            initialDelaySeconds: 15
#            periodSeconds: 10
#            timeoutSeconds: 5
#            failureThreshold: 30
